packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  tailwindcss: ^3.4.15
  typescript: ^5.7.3

  # Misc
  zod: ^3.24.1

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.67.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
